[build]
  command = "node ../../common/scripts/install-run-rush.js install && node ../../common/scripts/install-run-rush.js build --to thirstytherapy.com"
  publish = "__sapper__/export"
[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
