[package]
name = "obs-studio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "^0.3.0"
thiserror = "^1.0.30"
serde_json = { version = "^1.0.79", features = ["float_roundtrip"] }
