#!/usr/bin/env bash

set -e

out_dir=$(dirname "$0")

# Sync files from streaming user account for version control on this user
# account. Exclude some sensitive files. Requires this user account's sudo
# password.
sudo rsync --compress --links --recursive --times --verbose --exclude 'service.json' --exclude '*.bak' '/Users/thirstytherapy/Library/Application Support/obs-studio/basic' "$out_dir"/
sudo chown -R "$(whoami)" "$out_dir"/basic

shopt -s globstar
ini_files=("$out_dir"/basic/**/*.ini)
json_files=("$out_dir"/basic/**/*.json)

# Format OBS's compact JSON.
parallel 'python -m json.tool {} | sponge {}' ::: "${json_files[@]}"

# Exclude sensitive values from the files whose contents we mostly want. Note
# this is a blocklist approach. Sensitive values that aren't in this file's
# blocklist will still be output by this file. (It would be safer but more
# onerous for this file to instead maintain an allowlist).

# Exclude sensitive query params.
perl -p -i -e 's/&(password|room|tt\w+)(=[^&"]*)?|\?(password|room|tt\w+)(=[^&"]*)?&?//g' "${json_files[@]}"

# Exclude sensitive INI entries.
perl -n -i -e 'print unless /.*Token=.*/' "${ini_files[@]}"
