[build]
  command = "node common/scripts/install-run-rush.js install && node common/scripts/install-run-rush.js build --to browser-sources && node common/scripts/install-run-rush.js deploy --project browser-sources"
  publish = "../../common/deploy/apps/browser-sources/public/"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
